# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7da9d644805af85bd237c29b6490e3c3"
name = "grona-gardar-delivery-public"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_validations,write_delivery_customizations"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://example.com/api/delivery"
subpath = "gordon-delivery"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
